on:
  push:
  pull_request:
    branches:
      - master

name: build-pdfs

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    container: alanocallaghan/basicsworkflow2020-docker:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache downloads
        id: cache-downloads
        uses: actions/cache@v3
        with:
          path: downloads
          key: ${{ runner.os }}-downloads

      - name: Build
        run: |
          rmarkdown::render("Workflow.Rmd")
        shell: Rscript {0}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: |
            Workflow.pdf
